### ISSUE TITLE
End-to-end testing with Cypress

### ISSUE THREAD

**Issue by dallashuggins** [deptagency/algomart#192]
## Overview

Creating cypress tests

## Features

- [ ] Create, drop, seed database for tests
- [ ] Firebase authentication - signup, login, add/remove user
- [ ] Checkout payment flow for cards
- [ ] Checkout payment flow for wires
- [ ] Checkout payment flow for crypto
